### ISSUE TITLE
iperf3 compatibility

### ISSUE THREAD

**Issue by blm2008** [tpaskett/iperfspeed#2]
Several AREDN operators are unable to install iperfspeed after upgrading node firmware to 3.18.9.0 and installing the iperf3_3.5-1AREDN_mips_24kc.ipk package (iperf_2.0.5-1bbhn1_ar71xx.ipk is no longer compatible with much of the Ubiquiti hardware).

The ​iperfspeed_0.3_all.ipk file that we use is the from link on https://www.arednmesh.org/content/iperfspeed-v03, but it is not compatible with iperf3.

AREDN Forum Discussion Link: https://www.arednmesh.org/content/ver-59-da089ac-and-iperfspeed. 

Is there a compiled iperfspeed .ipk available that is compatible with iperf3?

**Comment by tpaskett** [comment]
I posted a new version on that thread, give it a try.

**Comment by blm2008** [comment]
Thanks, this worked on NBM5, NSM2, and RB-hAP hardware.  Thank you for the quick response.
