### ISSUE TITLE
Sort Nodelist in AREDN IperfSpeed

### ISSUE THREAD

**Issue by k1ky** [tpaskett/iperfspeed#4]
Feature request in IperfSpeed module: Sort the available node list alphabetically. This would be extremely helpful when looking for nodes in the list to test. Currently there appear to me no logical arrangement of the available nodes that are running IperfSpeed.

**Comment by nathantcampbell** [comment]
That would be a very nice addition for larger networks like the WVMN.

**Comment by k1ky** [comment]
This has been completed. Check the kn6plv GitHUb https://github.com/kn6plv/iperfspeed

**Comment by k1ky** [comment]
All done - see above.  Latest version now 0.8
